.github/workflows/license.sh, monad-raptorcast/wireshark/raptorcast.c
While working on the execution events SDK, I realized that we also need to check license headers for C/C++ files & headers (like `wrapper.h`). Although there don't seem to be any `hpp`, `c`, or `cpp` files in the consensus repo right now, feels reasonable to also add them here just in case.
EDIT: Turns out there was already a `c` file with a missing header!
=> Add C/C++ filetypes to CI license check

monad-dataplane/src/addrlist.rs, monad-dataplane/src/ban_expiry.rs, monad-dataplane/src/lib.rs, monad-dataplane/src/tcp/mod.rs, monad-dataplane/src/tcp/rx.rs, monad-dataplane/src/tcp/tx.rs, monad-node-config/src/network.rs, monad-node/src/main.rs, monad-raptorcast/src/lib.rs
this change ingegrates with discovery to update dataplane with trusted ips anytime
when epoch changes or when validator has a change in its api address.
connections from trusted ips will bypass total and per ip connections limits.
the other change is to disconnect peer that sent invalid message
=> monad-dataplane, monad-raptorcast: integrate disconnect / trusted peers api

monad-raptorcast/src/raptorcast_secondary/publisher.rs
- Addresses a crash first reported in [slack](https://category-labs.slack.com/archives/C0937BUM5GV/p1753802413547709)
- Adds unit test to reproduce the crash & make sure group scheduling continues as expected after resolution
=> Fix round gap crash

monad-state/src/lib.rs, monad-state/src/statesync.rs
Proposal iteration should be forward to avoid issuing excess blocksync requests
https://github.com/category-labs/monad-bft/issues/1556
=> Remove proposal iteration comment

monad-consensus-state/Cargo.toml, monad-consensus-state/src/lib.rs, monad-state/src/consensus.rs, monad-state/src/lib.rs
The upcoming leaders filter is used to tell the txpool in which future rounds the node will be proposing so it can preload account balances. Previously, it would produce all rounds regardless of the leader which causes the txpool preload manager to load account balances in every round. This change fixes the filtering condition so the txpool is only given the node's rounds.
Resolves https://github.com/category-labs/monad-bft/issues/2085.
=> Fix consensus state upcoming leaders filter

monad-chain-config/src/lib.rs
tn halt:
```toml
[high_qc.info]
id = "0x29c5864ef5f203ca6a0459c24fc64ac09dae88d7896437268fc34c618100a263"
round = 32026929
epoch = 609
parent_id = "0x9a0daaf43ca5b5d9253a764789f670adad72bf34ca732ff3c48aea57a5af8799"
parent_round = 32026928
```
=> Populate v0.10 tn fork round

monad-node/src/main.rs, monad-testground/src/executor.rs, monad-updaters/src/parent.rs
These metrics can be used as a canary for the main thread being overwhelmed. Concretely, (PARENT_TOTAL_EXEC_US + PARENT_TOTAL_POLL_US + STATE_TOTAL_UPDATE_US) / GAUGE_TOTAL_UPTIME_US is approximately how busy the main thread is.
=> Add metrics for elapsed CPU time

.github/workflows/test-command.yml
**Description:**
Added a GitHub Actions workflow that enables manual testing of external PRs via comment commands. When a maintainer comments `/test all` on any PR, it triggers the full test suite with access to private submodules.
External PRs from forks fail our CI because they cannot access:
- Private submodules required for compilation
- GitHub App tokens needed for authentication
This is a GitHub security feature that prevents untrusted code from accessing secrets.
This workflow solves the problem by allowing maintainers to manually trigger tests after code review, following the same pattern used by Kubernetes, Rust, and other major open source projects.
1. External contributor opens PR → CI fails with auth errors
2. Maintainer reviews the code
3. Maintainer comments `/test all` → …
=> ci: add manual test command for external PRs

monad-consensus-state/src/command.rs, monad-consensus-state/src/lib.rs, monad-consensus-types/src/lib.rs, monad-consensus-types/src/timeout.rs, monad-consensus/src/messages/message.rs, monad-consensus/src/pacemaker.rs, monad-consensus/src/validation/signing.rs, monad-mock-swarm/src/utils.rs, monad-testutil/src/proposal.rs
When sending a timeout with round=r, it's possible for high_tip.qc.round to be r-2. If the local high_certificate is QC(r-1), we need to support including QC(r-1) instead of TC(r-1).
=> Include last_round_qc if necessary

monad-consensus-state/src/command.rs, monad-consensus-state/src/lib.rs, monad-consensus/src/pacemaker.rs
Full-nodes currently only receive proposals. As a consequence, full-nodes will not bump their round even if the upstream validator has a higher QC/TC if there's no attached proposal.
=> Send AdvanceRound messages to full-nodes

monad-chain-config/src/lib.rs
```toml
[high_qc.info]
id = "0xa98e12563e9f03320202656b29552632304012986a37e552b188d8deff0f91f0"
round = 15643179
epoch = 312
parent_id = "0xaab03bc252d8ef8368dd9e05461ba0baec06c6d4e29561d040b498447e81a563"
parent_round = 15643178
```
=> Populate v0.10 mn fork round

Cargo.lock, monad-consensus/Cargo.toml, monad-consensus/src/validation/certificate_cache.rs, monad-consensus/src/validation/mod.rs, monad-consensus/src/validation/signing.rs, monad-consensus/tests/proposal.rs, monad-state/src/consensus.rs, monad-state/src/lib.rs
QCs/TCs/NECs are all expensive to verify, so we should cache recently verified ones. The current caching policy is very primitive and can be easily improved.
=> Cache recently verified quorum certificates

Cargo.lock, Cargo.toml, monad-blocksync/src/blocksync.rs, monad-consensus-state/src/lib.rs, monad-consensus/src/pacemaker.rs, monad-consensus/src/validation/signing.rs, monad-consensus/src/vote_state.rs, monad-raptorcast/Cargo.toml, monad-raptorcast/benches/raptor_bench.rs, monad-raptorcast/examples/service.rs, monad-raptorcast/src/udp.rs, monad-raptorcast/tests/encoder_error.rs, monad-raptorcast/tests/raptorcast_instance.rs, monad-state/src/lib.rs, monad-testground/src/main.rs, monad-testutil/src/validators.rs, monad-types/Cargo.toml, monad-types/src/lib.rs, monad-updaters/src/state_root_hash.rs, monad-validator/src/simple_round_robin.rs, monad-validator/src/validator_set.rs, monad-validator/src/weighted_round_robin.rs
This PR converts Stake type from u64 to U256 to match with execution. Added a custom serializer and deserializer for U256
Updated existing tests. Added tests for the custom serializer and deserializer. Added test to confirm equivalent leader schedule until fork.
=> Update Stake to U256

monad-consensus-state/src/lib.rs, monad-consensus-types/src/checkpoint.rs, monad-mock-swarm/tests/epoch.rs, monad-mock-swarm/tests/forkpoint.rs, monad-node/src/main.rs, monad-state/src/lib.rs, monad-types/src/lib.rs, monad-updaters/src/state_root_hash.rs, monad-updaters/src/triedb_state_root_hash.rs
This PR converts validator set locking at the end of an Epoch(N) from Epoch(N+2) to Epoch(N+1)
Updated forkpoint tests, mock swarm tests, and flexnet configs
=> Switch epoch lock from n+2 to n+1

Cargo.lock, Cargo.toml, monad-consensus-state/src/lib.rs, monad-consensus-types/src/block_validator.rs, monad-eth-block-policy/Cargo.toml, monad-eth-block-policy/src/lib.rs, monad-eth-block-validator/Cargo.toml, monad-eth-block-validator/src/lib.rs, monad-eth-testutil/src/lib.rs, monad-eth-txpool/Cargo.toml, monad-eth-txpool/src/pool/mod.rs, monad-eth-txpool/src/pool/transaction.rs, monad-system-calls/Cargo.toml, monad-system-calls/src/lib.rs, monad-system-calls/src/validator.rs
We need a special type of transaction for consensus to be able to communicate with execution about network related changes (epoch change for example). This PR adds the infrastructure on the consensus side to be able to generate such transactions and validate them differently than regular user transactions.
I've added unit tests for checking the validity of the system transactions based on transaction parameters. State specific tests will be added as system calls are added.
=> Add support for system transactions

.github/workflows/test-command.yml
Context:
The Test Command workflow was failing during the build because several expected environment variables were not defined in the runner context (toolchain + flags used by our build scripts and C/C++ deps).
What changed:
Define the minimal set of build variables at the job level so all steps inherit them:
CARGO_TERM_COLOR=always
CC=gcc-15, CXX=g++-15
CFLAGS=-march=haswell, CXXFLAGS=-march=haswell -DQUILL_ACTIVE_LOG_LEVEL=QUILL_LOG_LEVEL_CRITICAL
ASMFLAGS=-march=haswell
TRIEDB_TARGET=triedb_driver
Why:
Unblocks CI: resolves “missing env/undefined toolchain” failures.
=> ci(actions): fix Test Command workflow by defining required build env vars

monad-dataplane/src/lib.rs, monad-dataplane/src/udp.rs, monad-dataplane/tests/tests.rs
dataplane listens on two sockets and tags traffic that it sends to the consumer.
for sending we just select direct socket as source address if user specifies it over api, but otherwise the destination is selected in raptorcast
=> monad-dataplane: add udp socket for explicit direct messages

monad-peer-discovery/src/driver.rs
There's a log that's incorrectly being classified as error, causes some false positive by node operators
=> Remove incorrect error log

monad-node/src/main.rs, monad-peer-disc-swarm/src/driver.rs, monad-peer-disc-swarm/tests/peer_discovery.rs, monad-peer-discovery/src/discovery.rs, monad-peer-discovery/src/driver.rs, monad-peer-discovery/src/lib.rs, monad-peer-discovery/src/message.rs, monad-peer-discovery/src/mock.rs, monad-raptorcast/src/raptorcast_secondary/mod.rs
Closes https://github.com/category-labs/category-internal/issues/1772 (more details in the issue linked)
This introduces two new message types in peer discovery for (1) a full node to indicate that it wants to look for an upstream validator running as Publisher and (2) a validator indicating it's running as Publisher and has space
This PR allows a full node to keep looking for upstream validators until it finds 3 upstream that is running as Publisher mode. 
Tested in peer disc swarm
=> Full nodes connection

monad-rpc/Cargo.toml, monad-rpc/README.md, monad-rpc/src/cli.rs, monad-rpc/src/main.rs, monad-rpc/src/websocket/handler.rs
Adds a cli flag for operators to limit the number of subscriptions per WebSocket connection. The current default is `100` which is a very conservative default based on our most recent load testing results.
=> Add limit to websocket subscriptions

.github/workflows/rust.yml, debian/opt/monad/scripts/otel-config.yaml
- Disable otlp exporter for metrics
- Reduce the metric_expiration to 1m
=> otel default config file update

monad-raptorcast/src/lib.rs, monad-router-multi/src/lib.rs
Tested with:
```bash
while true; do RUST_LOG=info cargo test -p monad-raptorcast --test raptorcast_instance --release -- publish_to_full --nocapture; done
```
=> Deflake raptorcast tests

monad-eth-txpool-types/src/lib.rs, monad-eth-txpool/src/event_tracker.rs, monad-eth-txpool/src/metrics.rs, monad-eth-txpool/src/pool/pending/list.rs, monad-eth-txpool/src/pool/tracked/list.rs, monad-rpc/src/handlers/eth/txn.rs, monad-rpc/src/txpool/state.rs, monad-rpc/src/txpool/types.rs, monad-rpc/src/vpool.rs
The replaced event in the txpool event stream does not add a significant amount of value and can be modeled as an Insert event and a Drop event. This reduces the number of event variants, making the code simpler.
=> Remove replaced event from txpool events

monad-eth-txpool-executor/src/lib.rs, monad-eth-txpool-types/src/lib.rs, monad-eth-txpool/src/event_tracker.rs, monad-rpc/src/txpool/state.rs
After https://github.com/category-labs/monad-bft/pull/2061, each event has a single `tx_hash` associated with it that can be pulled out to make the event variants simpler.
The motivation for this change is to allow keying events by tx hash to deduplicate event patterns like `[Insert, Promote]`.
=> Refactor EthTxPoolEvent tx_hash

monad-eth-txpool-executor/src/ipc/mod.rs, monad-eth-txpool-executor/src/lib.rs, monad-eth-txpool-types/src/lib.rs, monad-eth-txpool/benches/common/controller.rs, monad-eth-txpool/benches/create_proposal.rs, monad-eth-txpool/benches/insert.rs, monad-eth-txpool/benches/update.rs, monad-eth-txpool/src/event_tracker.rs, monad-eth-txpool/tests/forward.rs, monad-eth-txpool/tests/pool.rs, monad-updaters/src/txpool.rs
This change keys txpool events by tx hash which enables deduplicating double events like `[Insert (Pending), Insert (Tracked)]` or `[Insert (Pending), Drop (some drop reason)]`.
This should improve more nuanced RPC `eth_sendTransaction` and `eth_sendRawTransaction` responses since RPC will respond with the first event received from txpool. In a situation like `[Insert (Pending), Drop (some drop reason)]`, previously, the event would not get deduplicated resulting in an `Ok` response. Now that events are tracked by tx hash, the `Drop` event will overwrite the `Insert` and thus the error will be immediately returned to the user.
=> Track txpool events by tx hash

monad-consensus-state/src/lib.rs, monad-mock-swarm/tests/forkpoint.rs, monad-state-backend/src/in_memory.rs, monad-state/src/lib.rs, monad-updaters/src/ledger.rs
Previously on startup, nodes would check if they had already finalized the current state root. This bound can be relaxed to checking whether the state root has been executed, as the proposed block will eventually get finalized after starting up. This change is expected to reduce the number of unnecessary statesyncs when restarting nodes.
=> Relax statesync short-circuit to root executed

monad-archive/src/archive_reader.rs, monad-archive/src/kvstore/triedb_reader.rs, monad-archive/src/model/block_data_archive.rs, monad-archive/src/model/index_repr.rs, monad-archive/src/model/logs_index.rs, monad-archive/src/model/mod.rs, monad-archive/src/model/tx_index_archive.rs, monad-archive/src/prelude.rs, monad-archive/src/workers/index_worker.rs, monad-rpc/src/chainstate/mod.rs, monad-rpc/src/handlers/debug.rs, monad-rpc/src/handlers/eth/block.rs, monad-rpc/src/handlers/eth/txn.rs, monad-rpc/src/handlers/mod.rs, monad-rpc/src/handlers/resources.rs, monad-rpc/src/jsonrpc.rs, monad-rpc/src/main.rs, monad-rpc/src/websocket/handler.rs
- Use try_get_x methods instead of get_x on ArchiveReader
- Improve chainstate -> handler mappings for readability via extension traits on error types
- Fix some warns in RPC
fixed https://github.com/category-labs/category-internal/issues/1845
=> RPC: Treat Archive NotFound the same as TrieDB NotFound

monad-dataplane/tests/address_family_mismatch.rs, monad-dataplane/tests/tests.rs
Port 9100/9022 is occupied on dev machines, causing dataplane tests to fail. Changed to different ports
ipv6 is not supported by dataplane or on dev machines. Removed ipv6 bind address from tests
=> Fix dataplane tests

monad-raptorcast/src/raptorcast_secondary/publisher.rs
An observation on stressnet is that a Publisher still continues to send group invites to full nodes that have already been pruned in peer discovery. We need to update the `peer_disc_full_nodes` list in secondary raptorcast to only take the active nodes in peer discovery, rather than then current behavior which is to continuously insert new nodes but never prune old nodes.
=> Update secondary raptorcast candidate list

monad-peer-disc-swarm/tests/peer_discovery.rs, monad-peer-discovery/src/discovery.rs, monad-raptorcast/src/lib.rs, monad-raptorcast/src/raptorcast_secondary/publisher.rs, monad-raptorcast/src/udp.rs, monad-raptorcast/src/util.rs, monad-router-multi/src/lib.rs
Approach: if a validator finds out that it's gonna fall out of the active set in the next epoch (this is known when next epoch validator set is available during epoch boundary block), then the validator will switch to FullNodeClient and starts participating in secondary raptorcast. After the epoch switch, it can then transition to a full node. 
Since this allows a node to participate in usual validator raptorcast and secondary raptorcast at the same time, it requires an additional bit to differentiate whether a chunk it receives is for the validator raptorcast or the secondary raptorcast in order to determine which other nodes to rebroadcast to. An additional bit is used in the raptorcast header for this purpose
Tested on stressnet with staking
=> Enable validator to full node role switch

monad-eth-txpool/src/pool/transaction.rs, monad-eth-txpool/tests/pool.rs
This change updates the txpool replacement policy to more closely match geth. The only difference is that this implementation allows txs with higher base fee and equal priority fee, while geth requires both to be strictly greater.
=> Update tx replacement policy to more closely match geth

monad-eth-block-policy/src/validation.rs, monad-eth-txpool-types/src/lib.rs, monad-eth-txpool/tests/pool.rs
This change introduces the 30M tx gas limit from the TFM spec. Additionally, a 192KB encoded tx length limit is added since max contract size is 128KB and, without support for blob data, there is likely no reasonable way to exceed this limit.
=> Add TFM validator to static tx validation

Cargo.lock
Nightly pipeline shows a vulnerability in one of our dependencies: https://jenkins.devcore4.com/job/monad-bft/job/nightly/528/consoleFull
=> Upgrade packages to remove vulnerability in tracing-subscriber

monad-rpc/src/handlers/eth/txn.rs
RPC needs to support 7702 type receipt. 
Flexnet tests here https://github.com/category-labs/monad-integration/pull/301
=> Support 7702 type receipt

monad-eth-block-policy/src/validation.rs
Cleanup: we already check 7702 authorization list length in `EthPragueForkValidation::validate` so we can remove this duplicated check.
Credits to Magnus for pointing this out
=> Remove duplicated 7702 check

monad-eth-txpool-executor/src/lib.rs, monad-node/src/main.rs, monad-updaters/src/lib.rs
Previously, `TokioTaskUpdater` required that some type passed as a generic `U` implement `Updater` which txpool happened to satisfy making the abstraction work. This bound however is unnecessary as the updater should simply require that some tokio task schedulable lambda take a command `C` receiver and an event `E` sender to emulate an Updater without strictly requiring a `Stream` implementation. This change updates the `TokioTaskUpdater` to relax this bound accordingly.
=> Relax trait bounds for TokioTaskupdater

monad-executor-glue/src/lib.rs, monad-mock-swarm/src/mock.rs, monad-peer-disc-swarm/src/driver.rs, monad-peer-disc-swarm/src/lib.rs, monad-peer-discovery/src/discovery.rs, monad-peer-discovery/src/driver.rs, monad-peer-discovery/src/lib.rs, monad-peer-discovery/src/mock.rs, monad-raptorcast/src/lib.rs, monad-raptorcast/src/raptorcast_secondary/client.rs, monad-raptorcast/src/raptorcast_secondary/mod.rs, monad-raptorcast/src/raptorcast_secondary/publisher.rs, monad-router-multi/src/lib.rs, monad-state/src/lib.rs, monad-updaters/src/config_loader.rs, monad-updaters/src/local_router.rs
Closes https://github.com/category-labs/category-internal/issues/1919. Tested on a single node. Extend support for the monad-debug-node reload config functionality such that we can also update prioritized full nodes without needing to restart the node.
Usage:
```
monad-debug-node --control-panel-ipc-path controlpanel.sock reload-config
```
=> Add support to dynamically reload prioritized full nodes

Cargo.lock, monad-peer-discovery/Cargo.toml, monad-peer-discovery/src/discovery.rs, monad-peer-discovery/src/ipv4_validation.rs, monad-peer-discovery/src/lib.rs
Closes https://github.com/category-labs/category-internal/issues/1777, audit issue raised by Zellic. This PR rejects IP addresses that are special addresses. For reference, geth also has similar checks https://github.com/ethereum/go-ethereum/blob/master/p2p/netutil/net.go#L185-L222
=> Reject reserved ips in peer discovery

monad-eth-txpool-executor/src/forward.rs, monad-eth-txpool-executor/src/lib.rs, monad-eth-txpool-executor/tests/executor.rs, monad-eth-txpool/src/pool/mod.rs
Previously, the `EGRESS_MAX_SIZE_BYTES` limit was soft in nature to allow a single large tx that exceeds the size limit to still get forwarded.
Since there is a tx limit checked in `ValidEthTransaction`, this change makes `EGRESS_MAX_SIZE_BYTES` a function of that max limit, raising the previous limit of 256KB to 384KB. Now, exceeding this limit will cause the tx to get dropped with a warn (as this would constitute a forwarding bug).
Resolves https://github.com/category-labs/category-internal/issues/1914.
=> Set txpool forwarding max byte limit to pool limit

debian/opt/monad/scripts/clear-old-artifacts.sh, debian/opt/monad/scripts/reset-workspace.sh
- Retain last 30days of `validators.toml` created per epoch
- Clear old `validators.toml` if the node runs hard-reset
=> feat: add validators.toml path

monad-ethcall/src/lib.rs, monad-node/src/main.rs, monad-rpc/src/cli.rs, monad-rpc/src/main.rs
Some eth call pool parameters were hard coded. Add cli options to configure both low and high eth call pools.
Minor refactoring to reduce number of function parameters.
=> Add configuration options for high eth call pool

monad-node/src/main.rs
When we start rolling out some bootstrap nodes (which are dedicated full nodes) to help public full nodes statesync when first starting up, we want to prevent these new public full nodes from pruning the name records of the bootstrap nodes, which prevent statesync from completing
=> Pin initial bootstrap nodes

monad-archive/Cargo.toml, monad-archive/src/archive_reader.rs, monad-archive/src/bin/monad-archive-checker/main.rs, monad-archive/src/cli.rs, monad-archive/src/kvstore/dynamodb.rs, monad-archive/src/kvstore/mod.rs, monad-archive/src/kvstore/mongo.rs, monad-archive/src/kvstore/s3.rs, monad-archive/src/prelude.rs, monad-archive/src/test_utils.rs, monad-archive/src/workers/file_checkpointer.rs
- Introduced kv connection string args
- Tidied cli parsing
- Added local Bucket testing against minio
- Now supports multi region s3, self-hosted minio, r2 and any other object store provider that has s3 api compatibility
This is an incremental step to more configurability. Next I'll introduce a config file instead of relying exclusively on complicated cli arguments
=> Archive: aws cli parsing works with any s3-api-compatible provider

monad-eth-block-policy/src/lib.rs, monad-eth-block-policy/src/validation.rs, monad-eth-testutil/src/lib.rs, monad-eth-txpool-executor/src/forward.rs, monad-eth-txpool-executor/tests/executor.rs, monad-eth-txpool/tests/forward.rs, monad-eth-txpool/tests/performance.rs, monad-eth-txpool/tests/pool.rs, monad-rpc/src/txpool/state.rs
Moves eth signers S1-S5 to monad-eth-testutil.
=> Consolidate eth signers to eth test utils

Cargo.lock, Cargo.toml, monad-crypto/src/hasher.rs, monad-dataplane/src/tcp/mod.rs, monad-dataplane/src/tcp/rx.rs, monad-dataplane/src/tcp/tx.rs, monad-types/src/lib.rs
i am using newer zerocopy in some follow up prs, they changed public api between versions so i pulled changes into a separate pr
=> deps: update zerocopy to 0.8
